/*
	Type XP1
	Authors: SeelingCat
*/

-----------------------------------------------
-- TraitModifiers
-----------------------------------------------

INSERT INTO TraitModifiers 
		(TraitType, 							ModifierId														)
VALUES	('MINOR_CIV_CSE_ENTERTAINMENT_TRAIT',	'MODIFIER_CSE_ENTERTAINMENT_FERRIS_WHEEL_AMENITY_ETHIOPIA'		),
		('MINOR_CIV_CSE_ENTERTAINMENT_TRAIT',	'MODIFIER_CSE_ENTERTAINMENT_AQUARIUM_AMENITY_ETHIOPIA'			),
		('MINOR_CIV_CSE_ENTERTAINMENT_TRAIT',	'MODIFIER_CSE_ENTERTAINMENT_AQUATICS_CENTER_AMENITY_ETHIOPIA'	);

-----------------------------------------------
-- Modifiers
-----------------------------------------------

INSERT INTO Modifiers 
		(ModifierId,															ModifierType,								SubjectRequirementSetId					)
VALUES	('MODIFIER_CSE_ENTERTAINMENT_FERRIS_WHEEL_AMENITY_ETHIOPIA',			'MODIFIER_ALL_PLAYERS_ATTACH_MODIFIER',		'PLAYER_HAS_LARGEST_INFLUENCE'			),
		('MODIFIER_CSE_ENTERTAINMENT_FERRIS_WHEEL_AMENITY_MOD_ETHIOPIA',		'MODTYPE_CSE_ENTERTAINMENT_AMENITY',		'REQSET_CSE_CITY_HAS_FERRIS_WHEEL'		),
		('MODIFIER_CSE_ENTERTAINMENT_AQUARIUM_AMENITY_ETHIOPIA',				'MODIFIER_ALL_PLAYERS_ATTACH_MODIFIER',		'PLAYER_HAS_LARGEST_INFLUENCE'			),
		('MODIFIER_CSE_ENTERTAINMENT_AQUARIUM_AMENITY_MOD_ETHIOPIA',			'MODTYPE_CSE_ENTERTAINMENT_AMENITY',		'REQSET_CSE_CITY_HAS_AQUARIUM'			),
		('MODIFIER_CSE_ENTERTAINMENT_AQUATICS_CENTER_AMENITY_ETHIOPIA',			'MODIFIER_ALL_PLAYERS_ATTACH_MODIFIER',		'PLAYER_HAS_LARGEST_INFLUENCE'			),
		('MODIFIER_CSE_ENTERTAINMENT_AQUATICS_CENTER_AMENITY_MOD_ETHIOPIA',		'MODTYPE_CSE_ENTERTAINMENT_AMENITY',		'REQSET_CSE_CITY_HAS_AQUATICS_CENTER'	);

-----------------------------------------------
-- ModifierArguments
-----------------------------------------------

INSERT INTO ModifierArguments
		(ModifierId,															Name,			Value																)
VALUES	('MODIFIER_CSE_ENTERTAINMENT_FERRIS_WHEEL_AMENITY_ETHIOPIA',			'ModifierId',	'MODIFIER_CSE_ENTERTAINMENT_FERRIS_WHEEL_AMENITY_MOD_ETHIOPIA'		),
		('MODIFIER_CSE_ENTERTAINMENT_FERRIS_WHEEL_AMENITY_MOD_ETHIOPIA',		'Amount',		1																	),
		('MODIFIER_CSE_ENTERTAINMENT_AQUARIUM_AMENITY_ETHIOPIA',				'ModifierId',	'MODIFIER_CSE_ENTERTAINMENT_AQUARIUM_AMENITY_MOD_ETHIOPIA'			),
		('MODIFIER_CSE_ENTERTAINMENT_AQUARIUM_AMENITY_MOD_ETHIOPIA',			'Amount',		1																	),
		('MODIFIER_CSE_ENTERTAINMENT_AQUATICS_CENTER_AMENITY_ETHIOPIA',			'ModifierId',	'MODIFIER_CSE_ENTERTAINMENT_AQUATICS_CENTER_AMENITY_MOD_ETHIOPIA'	),
		('MODIFIER_CSE_ENTERTAINMENT_AQUATICS_CENTER_AMENITY_MOD_ETHIOPIA',		'Amount',		1																	);